### ISSUE TITLE
Surgery Skill rises constantly when using Baroverhaul's Boosters

### ISSUE THREAD

**Issue by Hunter20k** [MrCurlyFries/NT-Surgery-Plus-Ultra-name-pending#2]
So I already know this is a bit of a stretch to even make this issue known but I figure its better to ask here since the issue only applies to the surgeon class, but whenever using one of the boosters from Baroverhaul, such as a strength or intelligence booster, Surgery skill rises constantly.

We figured this issue out in our campaign on the Argus Dynamics Server where one of our surgeons has all 5 strength boosters applied and is gaining surgery skill at an insane rate, having a bonus of over 4000 surgery skill. As for why this happens, we have no clue. If you could help this would be great 

If you need any more information feel free to contact either hunter20k (Currently COB Conte) or cannibalsmiley (Currently P Eckmeier) on the Argus Dynamics discord, which I will link below

https://discord.gg/tBrsDh5q

I've attached a clip that showcases the issue below, I clipped this in a sandbox with only 2 intelligence boosters applied.
https://medal.tv/games/barotrauma/clips/iQ4HTI7QC3qoeGwJe?invite=cr-MSxLVW4sMjUwOTU2NjMzLA

**Comment by MrCurlyFries** [comment]
Heya! Thanks for letting me know, can't say I have too much experience with Baroverhaul, but i'll look into this in the near future and get back to you.

**Comment by MrCurlyFries** [comment]
Issue can be replicated with a load order of
Neurotrauma
NT Surgery Plus Ultra
Baroverhaul

Result is as stated Surgical skill on a surgeon ticks up when injected by an intelligence booster
Stacking the booster does not

Sidenote, applying an intelligence booster to a bot in single player from another character (other players unknown atm) will apply the perk, but not the skill points or the bug

Seems to have funky/non linear interactions with custom skills in general, ie. Hungry Europans Butchery and Cooking skill or customs skills given through the console giveskill command

**Comment by MrCurlyFries** [comment]
Disabling lua dosen't even stop it... hmm

I cannot find how its interacting with custom skills, so i'd assume its a fun engine related bug.
I'm going to try and remake the item to give the skills a different way.

**Comment by MrCurlyFries** [comment]
Update - Re:Ydrec on the Luatrauma discord
"Well, most skill bonuses are essentially
Component Update loop
User.GetThisSkill("skillname")
math
bonus from skill 
Also there is stattypes enum which only has stats for vanilla skills, so talent bonuses cant be properly defined for custom skills"

So, why its scaling the surgical skill? no idea, possibly an engine bug?
The only way I can forsee a fix is to remake the item, possibly using something along the lines of hidden talents and using a character specific int or something. - I'll give it a try, no promises.
